### 1.1 Получить список всех пользователей
GET http://127.0.0.1:8000/api/users/
Content-Type: application/json

### 1.2 Создать нового пользователя
POST http://127.0.0.1:8000/api/user/
Content-Type: application/json

{
    "first_name": "Иван",
    "last_name": "Иванов",
    "phone_number": "+79991234567",
    "email": "ivan@example.com",
    "address": "Москва, ул. Примерная, 1",
    "login": "Ivan",
    "password": "qwerty123233"
}

### 1.3 Получить конкретного пользователя (замените <id> на реальный ID)
GET http://127.0.0.1:8000/api/user/1/
Content-Type: application/json

### 1.4 Обновить пользователя (PUT - полное обновление, PATCH - частичное)
PATCH  http://127.0.0.1:8000/api/user/1/
Content-Type: application/json

{
    "first_name": "Иван",
    "last_name": "Иванов",
    "phone_number": "+79991234567",
    "email": "ivan.new@example.com",
    "address": "Москва, ул. Обновлённая, 2"
}

### 1.5 Удаление пользователя
DELETE http://127.0.0.1:8000/api/user/1/
Content-Type: application/json



### 2.1 Получение категорий
GET http://127.0.0.1:8000/api/categories/

### 2.2. Создание категории
POST http://127.0.0.1:8000/api/categories/
Content-Type: application/json

{
    "title": "Стройматериалы"
} 

### 2.3 Обновление названия категории
PATCH http://127.0.0.1:8000/api/categories/1/
Content-Type: application/json

{
    "title": "Бытовая техника"
}

### 2.4 Удаление категории
DELETE http://127.0.0.1:8000/api/categories/1/


### 3.1 Получить все магазины
GET http://127.0.0.1:8000/api/shops/

### 3.2 Создать магазин
POST http://127.0.0.1:8000/api/shops/
Content-Type: application/json

{
    "title": "Электротехника М2",
    "description": "Описание моего магазина",
    "url": "https://my-shop.example.com",
    "user_id": 1
}

### 3.3 Обновление магазина
PATCH http://127.0.0.1:8000/api/shops/5/
Content-Type: application/json

{
    "title": "Химия для дачи",
    "description": "Описание моего магазина",
    "url": "https://my-shop.example.com",
    "user_id": 1
}

### 3.4 Удаление магазина
DELETE http://127.0.0.1:8000/api/shops/1/


### 4.1 Получение продукта
GET http://127.0.0.1:8000/api/products/
Accept: application/json

### 4.2 Создание продукта
POST http://127.0.0.1:8000/api/products/
Content-Type: application/json

{
  "title": "Бензопила",
  "category": 1,
  "description": "Делает всё",
  "shop": 1,
  "quantity": 1,
  "price": 1000
}

### 4.3 Обновление продукта
PATCH http://127.0.0.1:8000/api/products/1/
Content-Type: application/json

{
  "title": "МФУ",
  "price": 1000000,
  "quantity": 1
}

### 4.4 Удаление продукта
DELETE http://127.0.0.1:8000/api/products/9/


### 5.1 Получение корзины
GET http://127.0.0.1:8000/api/buskets/39/


### 5.2 Добавление товара в корзину пользователя
POST http://127.0.0.1:8000/api/buskets/
Content-Type: application/json

{
  "user": 1,
  "product": 1,
  "quantity": 1
}

### 5.3 Удаление товара из корзины
DELETE http://127.0.0.1:8000/api/buskets/
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 1
}


### 6.1 Получение заказов пользователя
GET http://127.0.0.1:8000/api/orders/user/1/

### 6.2 Создание заказа пользователем
POST http://127.0.0.1:8000/api/orders/
Content-Type: application/json

{
  "user": 1
}

### 6.3 Удаление заказа пользователя
DELETE http://127.0.0.1:8000/api/orders/1/
