# Generated by Django 5.2 on 2025-04-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['title'], 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='usercredentials',
            options={'ordering': ['login'], 'verbose_name': 'Учётные данные', 'verbose_name_plural': 'Учётные данные'},
        ),
    ]
