# Generated by Django 5.2 on 2025-04-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_user_address_order_orderposition_busket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderposition',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
    ]
