# Generated by Django 5.2 on 2025-07-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_alter_order_options_alter_orderposition_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='created', max_length=20),
        ),
    ]
